# Generated by Django 5.0.14 on 2026-06-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
