# Generated by Django 5.0.14 on 2026-02-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('admin', 'Admin')], default='doctor', help_text='User role: doctor or admin', max_length=10),
        ),
    ]
