// AUTO-GENERATED by backend/ml_models/export_to_c.py — DO NOT HAND-EDIT.
// Regenerate after every retrain:  python backend/ml_models/export_to_c.py
// Source: backend/ml_models/lgbm_tremor_model.pkl  (Feature 053 — BINARY)
#pragma once
#include <cstdint>

namespace tremor_model {

constexpr int   NUM_CLASS       = 2;   // semantic classes: 0=Non-Tremor, 1=Tremor
constexpr int   NUM_RAW_OUTPUTS = 1;   // binary -> 1 tree series; proba = sigmoid(raw)
constexpr int   NUM_TREES    = 300;   // = n_estimators (one series for binary)
constexpr int   NUM_NODES    = 37500;
constexpr int   NUM_FEATURES = 66;
constexpr float SAMPLE_RATE_HZ = 100.0f;
constexpr int   WINDOW_SIZE  = 128;

// Per-node flat arrays (all trees concatenated). Leaf iff feature[i] < 0.
extern const int16_t feature[NUM_NODES];
extern const float   threshold[NUM_NODES];
extern const int32_t left[NUM_NODES];
extern const int32_t right[NUM_NODES];
extern const uint8_t default_left[NUM_NODES];
extern const float   leaf_value[NUM_NODES];

// Root node index of each sub-tree. Binary: all trees sum into one raw score.
extern const int32_t tree_root[NUM_TREES];
// Additive base/init score: raw = init_score[0] + sum(leaf); p_tremor = sigmoid(raw).
extern const float   init_score[NUM_RAW_OUTPUTS];

// Causal Butterworth band-pass SOS (matches backend/ml_models/features_lgbm.py).
// 0.5-20.0 Hz, 4th-order, 4 biquad sections at 100 Hz.
constexpr int   BANDPASS_N_SECTIONS = 4;
// Each row: {b0, b1, b2, a0, a1, a2} (scipy SOS order; a0 == 1).
extern const float bandpass_sos[BANDPASS_N_SECTIONS][6];

} // namespace tremor_model
