# Generated by Django 5.0.14 on 2026-02-18 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('patients', '0002_remove_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorFaultEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('fault_type', models.CharField(choices=[('overcurrent', 'Overcurrent'), ('stall', 'Stall')], max_length=16)),
                ('rpm_at_fault', models.IntegerField(blank=True, null=True)),
                ('current_at_fault', models.FloatField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_faults', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='motor_fault_events', to='devices.device')),
                ('patient', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='motor_fault_events', to='patients.patient')),
            ],
            options={
                'db_table': 'cmg_motor_fault_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['device', '-occurred_at'], name='cmg_fault_device_ts_idx'), models.Index(fields=['patient', '-occurred_at'], name='cmg_fault_patient_ts_idx'), models.Index(fields=['acknowledged', '-occurred_at'], name='cmg_fault_ack_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='MotorTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('rpm', models.IntegerField()),
                ('current_a', models.FloatField()),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('starting', 'Starting'), ('running', 'Running'), ('fault', 'Fault')], max_length=12)),
                ('fault_type', models.CharField(blank=True, choices=[('overcurrent', 'Overcurrent'), ('stall', 'Stall')], max_length=16, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='motor_telemetry', to='devices.device')),
                ('patient', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='motor_telemetry', to='patients.patient')),
            ],
            options={
                'db_table': 'cmg_motor_telemetry',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='cmg_device_ts_desc_idx'), models.Index(fields=['patient', '-timestamp'], name='cmg_patient_ts_desc_idx')],
            },
        ),
    ]
