# Generated by Django 5.0.14 on 2026-02-19 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmg', '0001_add_motor_models'),
        ('devices', '0001_initial'),
        ('patients', '0002_remove_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GimbalCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_center_deg', models.FloatField(default=0.0)),
                ('roll_center_deg', models.FloatField(default=0.0)),
                ('pitch_min_deg', models.FloatField(default=-30.0)),
                ('pitch_max_deg', models.FloatField(default=30.0)),
                ('roll_min_deg', models.FloatField(default=-20.0)),
                ('roll_max_deg', models.FloatField(default=20.0)),
                ('rate_limit_deg_per_sec', models.FloatField(default=45.0)),
                ('config_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gimbal_calibration', to='devices.device')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gimbal_calibrations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cmg_gimbal_calibration',
            },
        ),
        migrations.CreateModel(
            name='GimbalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_deg', models.FloatField()),
                ('roll_deg', models.FloatField()),
                ('pitch_status', models.CharField(choices=[('idle', 'Idle'), ('moving', 'Moving'), ('fault', 'Fault')], max_length=8)),
                ('roll_status', models.CharField(choices=[('idle', 'Idle'), ('moving', 'Moving'), ('fault', 'Fault')], max_length=8)),
                ('device_timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gimbal_state', to='devices.device')),
            ],
            options={
                'db_table': 'cmg_gimbal_state',
            },
        ),
        migrations.CreateModel(
            name='ServoCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_pitch_deg', models.FloatField(blank=True, null=True)),
                ('target_roll_deg', models.FloatField(blank=True, null=True)),
                ('is_home_command', models.BooleanField(default=False)),
                ('rate_limit_snap', models.FloatField()),
                ('pitch_min_snap', models.FloatField()),
                ('pitch_max_snap', models.FloatField()),
                ('roll_min_snap', models.FloatField()),
                ('roll_max_snap', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='servo_commands', to='devices.device')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_servo_commands', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='servo_commands', to='patients.patient')),
            ],
            options={
                'db_table': 'cmg_servo_commands',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['device', '-issued_at'], name='cmg_servo_device_ts_idx'), models.Index(fields=['patient', '-issued_at'], name='cmg_servo_patient_ts_idx')],
            },
        ),
    ]
