# Generated by Django 5.0.14 on 2026-02-19 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmg', '0002_add_gimbal_models'),
        ('devices', '0001_initial'),
        ('patients', '0002_remove_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PIDConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kp_pitch', models.FloatField(default=0.0)),
                ('ki_pitch', models.FloatField(default=0.0)),
                ('kd_pitch', models.FloatField(default=0.0)),
                ('kp_roll', models.FloatField(default=0.0)),
                ('ki_roll', models.FloatField(default=0.0)),
                ('kd_roll', models.FloatField(default=0.0)),
                ('config_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pid_config', to='devices.device')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pid_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cmg_pid_config',
            },
        ),
        migrations.CreateModel(
            name='SuppressionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('interrupted', 'Interrupted')], default='active', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('kp_pitch_snap', models.FloatField()),
                ('ki_pitch_snap', models.FloatField()),
                ('kd_pitch_snap', models.FloatField()),
                ('kp_roll_snap', models.FloatField()),
                ('ki_roll_snap', models.FloatField()),
                ('kd_roll_snap', models.FloatField()),
                ('device', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='suppression_sessions', to='devices.device')),
                ('patient', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='suppression_sessions', to='patients.patient')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_suppression_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cmg_suppression_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SuppressionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_timestamp', models.DateTimeField()),
                ('raw_amplitude_deg', models.FloatField()),
                ('residual_amplitude_deg', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='suppression_metrics', to='devices.device')),
                ('session', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='suppression_metrics', to='cmg.suppressionsession')),
            ],
            options={
                'db_table': 'cmg_suppression_metrics',
                'ordering': ['-device_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='suppressionsession',
            index=models.Index(fields=['device', '-started_at'], name='cmg_supp_device_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='suppressionsession',
            index=models.Index(fields=['patient', '-started_at'], name='cmg_supp_patient_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='suppressionsession',
            index=models.Index(fields=['status', '-started_at'], name='cmg_supp_status_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='suppressionmetric',
            index=models.Index(fields=['session', 'device_timestamp'], name='cmg_metric_session_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='suppressionmetric',
            index=models.Index(fields=['device', 'device_timestamp'], name='cmg_metric_device_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='suppressionmetric',
            index=models.Index(fields=['created_at'], name='cmg_metric_created_idx'),
        ),
    ]
