# Generated by Django 5.0.14 on 2026-02-15 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this inference request', primary_key=True, serialize=False)),
                ('model_used', models.CharField(help_text='Model name: rf, svm, lstm, or cnn_1d', max_length=50)),
                ('prediction', models.BooleanField(help_text='Tremor detected (True) or not detected (False)')),
                ('severity', models.IntegerField(help_text='Severity level: 0 (none), 1 (mild), 2 (moderate), 3 (severe)')),
                ('confidence_score', models.FloatField(blank=True, help_text='Model confidence score (0.0-1.0) - P3 feature', null=True)),
                ('inference_time_ms', models.IntegerField(blank=True, help_text='Inference duration in milliseconds - P3 feature', null=True)),
                ('input_shape', models.CharField(help_text="Input data shape for debugging (e.g., '(128, 6)' or '(18,)')", max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the inference was performed')),
                ('user', models.ForeignKey(help_text='User who made the inference request (doctor or patient)', on_delete=django.db.models.deletion.CASCADE, related_name='inference_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inference Log',
                'verbose_name_plural': 'Inference Logs',
                'db_table': 'inference_inferencelog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='idx_user_time'), models.Index(fields=['model_used'], name='idx_model'), models.Index(fields=['-timestamp'], name='idx_time')],
            },
        ),
    ]
