# Generated by Django 5.0.14 on 2026-02-15 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField()),
                ('session_duration', models.DurationField()),
                ('sensor_data', models.JSONField()),
                ('ml_prediction', models.JSONField(blank=True, help_text='ML model prediction results (severity, confidence)', null=True)),
                ('ml_predicted_at', models.DateTimeField(blank=True, help_text='Timestamp when ML prediction was generated', null=True)),
                ('received_via_mqtt', models.BooleanField(default=False, help_text='True if session data arrived via MQTT real-time pipeline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biometric_sessions', to='devices.device')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_sessions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Biometric Session',
                'verbose_name_plural': 'Biometric Sessions',
                'db_table': 'biometric_sessions',
                'ordering': ['-session_start'],
                'indexes': [models.Index(fields=['patient', 'session_start'], name='biometric_s_patient_3d0c93_idx'), models.Index(fields=['device', 'session_start'], name='biometric_s_device__e2bc2e_idx')],
            },
        ),
    ]
