# Generated by Django 5.0.14 on 2026-02-18 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0001_initial'),
        ('patients', '0002_remove_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('aX', models.FloatField()),
                ('aY', models.FloatField()),
                ('aZ', models.FloatField()),
                ('gX', models.FloatField()),
                ('gY', models.FloatField()),
                ('gZ', models.FloatField()),
                ('flex_1', models.FloatField()),
                ('flex_2', models.FloatField()),
                ('flex_3', models.FloatField()),
                ('flex_4', models.FloatField()),
                ('flex_5', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_readings', to='patients.patient')),
            ],
            options={
                'db_table': 'biometric_readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient', 'timestamp'], name='biometric_r_patient_848427_idx'), models.Index(fields=['timestamp'], name='biometric_r_timesta_9ca387_idx')],
            },
        ),
    ]
