# Generated by Django 5.0.14 on 2026-02-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0002_add_biometricreading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricreading',
            name='flex_1',
        ),
        migrations.RemoveField(
            model_name='biometricreading',
            name='flex_2',
        ),
        migrations.RemoveField(
            model_name='biometricreading',
            name='flex_3',
        ),
        migrations.RemoveField(
            model_name='biometricreading',
            name='flex_4',
        ),
        migrations.RemoveField(
            model_name='biometricreading',
            name='flex_5',
        ),
    ]
