# Generated by Django 5.0.14 on 2026-02-18 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0003_remove_flex_fields'),
        ('patients', '0002_remove_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TremorMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('tremor_detected', models.BooleanField()),
                ('dominant_axis', models.CharField(choices=[('aX', 'aX'), ('aY', 'aY'), ('aZ', 'aZ'), ('gX', 'gX'), ('gY', 'gY'), ('gZ', 'gZ')], max_length=3)),
                ('dominant_freq_hz', models.FloatField(blank=True, null=True)),
                ('dominant_amplitude', models.FloatField()),
                ('amp_aX', models.FloatField()),
                ('amp_aY', models.FloatField()),
                ('amp_aZ', models.FloatField()),
                ('amp_gX', models.FloatField()),
                ('amp_gY', models.FloatField()),
                ('amp_gZ', models.FloatField()),
                ('freq_aX', models.FloatField(blank=True, null=True)),
                ('freq_aY', models.FloatField(blank=True, null=True)),
                ('freq_aZ', models.FloatField(blank=True, null=True)),
                ('freq_gX', models.FloatField(blank=True, null=True)),
                ('freq_gY', models.FloatField(blank=True, null=True)),
                ('freq_gZ', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tremor_metrics', to='patients.patient')),
            ],
            options={
                'db_table': 'tremor_metrics',
                'ordering': ['-window_start'],
                'indexes': [models.Index(fields=['patient', 'window_start'], name='tremor_metr_patient_2a68d9_idx'), models.Index(fields=['window_start'], name='tremor_metr_window__ee6a75_idx')],
            },
        ),
    ]
